### ISSUE TITLE
Chrome-tracing error on a recursive make directory

### ISSUE THREAD

**Issue by DianaOlympos** [Arrowbox/makegrind#5]
## Expected Behavior
With a recursive make set of json (outputted by remake), `makegrind chrome-tracing`  produce a chrome-tracing output

## Actual Behavior
Crash

```
makegrind -v chrome-tracing
INFO: Loading files
INFO: Combining graphs
INFO: Generating chrome-traching file
Traceback (most recent call last):
  File "/home/DianaO/.local/bin/makegrind", line 33, in <module>
    sys.exit(load_entry_point('makegrind==0.1.dev7+g8237762.d20230120', 'console_scripts', 'makegrind')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/click/decorators.py", line 38, in new_func
    return f(get_current_context().obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/DianaO/.local/lib/python3.11/site-packages/makegrind/__main__.py", line 151, in chrome_tracing
    makegrind.dump_chrome_tracing(graph, outfile)
  File "/home/DianaO/.local/lib/python3.11/site-packages/makegrind/output.py", line 102, in dump_chrome_tracing
    process(graph.targets.info(node))
  File "/home/DianaO/.local/lib/python3.11/site-packages/makegrind/output.py", line 90, in process
    process(child)
  File "/home/DianaO/.local/lib/python3.11/site-packages/makegrind/output.py", line 90, in process
    process(child)
  File "/home/DianaO/.local/lib/python3.11/site-packages/makegrind/output.py", line 90, in process
    process(child)
  [Previous line repeated 6 more times]
  File "/home/DianaO/.local/lib/python3.11/site-packages/makegrind/output.py", line 84, in process
    "ts": round(node.start.timestamp() * 1000000),
                ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'bool' object has no attribute 'timestamp'
```

## Steps to Reproduce the Problem

1. get a recursive make set of build.*.json
2. `makegrind chrome-tracing`

## Specifications

- Version: Python 3.11.1
- Platform: Fedora amd64

**Comment by DianaOlympos** [comment]
I am going to explore this one myself more tomorrow, but I wanted to open it in case someone that understands this stuff better could find a solution faster.
